### ISSUE TITLE
Add test infra jobs for Sync Controller

### ISSUE THREAD

**Issue by nilekhc** [kubernetes-sigs/secrets-store-sync-controller#3]
Setup CI jobs in test infra similar to - https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs/secrets-store-csi-driver

**Comment by nilekhc** [comment]
https://github.com/kubernetes/test-infra/pull/32706 added lint and unit test jobs.

**Comment by nilekhc** [comment]
https://github.com/kubernetes/test-infra/pull/32871 added image-scan job

**Comment by AlexanderStocks** [comment]
https://github.com/kubernetes/test-infra/pull/33115 make infra jobs mandatory

**Comment by AlexanderStocks** [comment]
Should this be closed now?

**Comment by nilekhc** [comment]
> Should this be closed now?

/close
