### ISSUE TITLE
Inconsistency between README instructions and Makefile output

### ISSUE THREAD

**Issue by omerap12** [kubernetes-sigs/secrets-store-sync-controller#86]
The README.md file provides instructions for deploying the controller (https://github.com/kubernetes-sigs/secrets-store-sync-controller?tab=readme-ov-file#deploy-the-controller). However, there are discrepancies between the instructions and the actual outcomes of the commands.
Specifically, when executing the command: `VERSION=e2e make docker-build`
The resulting Docker image is named controller:e2e instead of secrets-store-sync-controller:e2e as stated in the documentation.
This inconsistency between the documentation and the actual behavior may lead to confusion for users attempting to deploy the controller.

**Comment by jayeshmahajan** [comment]
PR https://github.com/kubernetes-sigs/secrets-store-sync-controller/pull/87

**Comment by aramase** [comment]
Closed with https://github.com/kubernetes-sigs/secrets-store-sync-controller/pull/87

/close
